### PR TITLE
added repo tools, create utils modules, added comments and refactoring the strictCheck feature

### PR DESCRIPTION
**Pull request by jeanpierrecarvalho**
Hi!

Today, using the is-glob in another package I verified the package it's outdated. I decided add some repo tools and refactoring the code.

I started to added to dev packages:

- commitlint
- husky
- lint-staged
- enforce-branch-name
- prettier
- eslint

I added config files for each package and two hooks for the husky package: pre-commit and commit-msg

After that, I refactored the code using the latest eslint convention.

I created two utils modules to remove all strictCheck and relaxed for the index file.

I added the jest lib and the jest benchmark, it's possible run the tests using:

**yarn run jest** or **yarn run jest:watch** or **yarn run jest:coverage** or **yarn run jest:benchmark** 

**Finally I refactored the strictCheck functionality:**

```
   if (str[index] === '[' && str[index + 1] !== ']') {
     if (closeSquareIndex === -1 || closeSquareIndex < index) {
       closeSquareIndex = str.indexOf(']', index)
     }
     if (closeSquareIndex > index) {
       backSlashIndex = str.indexOf('\\', index)
       if (backSlashIndex === -1 || backSlashIndex > closeSquareIndex) {
         return true
       }
     }
   }
```

- Removing the unnecessary check for closeSquareIndex !== -1, as this is already checked in the second if statement.
- Removing the unnecessary assignment of closeSquareIndex, as it is only used if the first if statement is true.
- Removing the unnecessary second check for backSlashIndex === -1 || backSlashIndex > closeSquareIndex, as this is the same as the first check.
- Moving the assignment of backSlashIndex outside the second if statement to avoid unnecessary reassignments.

```
   if (str[index] === '{' && str[index + 1] !== '}') {
     closeCurlyIndex = str.indexOf('}', index)
     if (closeCurlyIndex !== -1 && closeCurlyIndex > index) {
       backSlashIndex = str.indexOf('\\', index)
       if (backSlashIndex === -1 || backSlashIndex > closeCurlyIndex) {
         return true
       }
     }
   }
```

- Removing the unnecessary check for closeCurlyIndex !== -1, as this is already checked in the second if statement.
- Removing the unnecessary assignment of closeCurlyIndex, as it is only used if the first if statement is true.

```
   if (
     str[index] === '(' &&
     str[index + 1] === '?' &&
     /[:!=]/.test(str[index + 2]) &&
     str[index + 3] !== ')'
   ) {
     closeParenIndex = str.indexOf(')', index)
     if (closeParenIndex !== -1 && closeParenIndex > index) {
       backSlashIndex = str.indexOf('\\', index)
       if (backSlashIndex === -1 || backSlashIndex > closeParenIndex) {
         return true
       }
     }
   }
```

- Removing the unnecessary check for closeParenIndex !== -1, as this is already checked in the second if statement.
- Removing the unnecessary assignment of closeParenIndex, as it is only used if the first if statement is true.

 ```
  if (str[index] === '(' && str[index + 1] !== '|') {
     if (pipeIndex === -1 || pipeIndex < index) {
       pipeIndex = str.indexOf('|', index)
     }
     if (pipeIndex !== -1 && str[pipeIndex + 1] !== ')') {
       closeParenIndex = str.indexOf(')', pipeIndex)
       if (closeParenIndex > pipeIndex) {
         backSlashIndex = str.indexOf('\\', pipeIndex)
         if (backSlashIndex === -1 || backSlashIndex > closeParenIndex) {
           return true
         }
       }
     }
   }
```

- Removing the unnecessary check for pipeIndex !== -1, as this is already checked in the second if statement.
- Moving the assignment of pipeIndex inside the first if statement to avoid unnecessary reassignments.
- Removing the unnecessary if statement around the assignment of closeParenIndex, as it is only used if pipeIndex !== -1.

```
if (str[index] === '\\') {
     const open = str[index + 1]
     const close = chars[open]
     if (close) {
       const n = str.indexOf(close, index + 2)
       if (n !== -1) {
         index = n + 1
         if (str[index] === '!') {
           return true
         }
       }
     } else {
       index += 2
       if (str[index] === '!') {
         return true
       }
     }
   } else {
     index++
   }
```
- Splitting the code into two branches based on whether close is defined.
- Moving the check for str[index] === '!' inside the branch where close is defined to avoid unnecessary checks.
- Incrementing index by 2 inside the branch where close is defined to avoid unnecessary increments.

Any questions, I'm here to discuss and validate the solution with you.

### CODE REVIEW

**Comment by jeanpierrecarvalho** [comment]
I forgot to mention. NodeJS >= 8.0 it's a must to have.

The github actions had the previous nodejs versions and it's a reason for the failure.

I think it's secure to change this in the next package version.

**Comment by phated** [comment]
It looks like you started branching from the wrong place. If you want to split these out into individual PRs, I can address them individually.

Some of the stuff isn't going to make it (like husky and commitlint) but some of the stuff (like GHA) can land.

**Comment by jeanpierrecarvalho** [comment]
Hi @phated,

Nice to meet you! Sure, I will split in different PR today.

Thanks for the quick answer!

**Comment by phated** [comment]
Sounds great 😄 Thanks for taking the time!

**Pull request closed without merging**
